language: cpp
sudo: required
compiler:
 - clang
os:
 - linux
dist: focal
arch:
  - arm64
  - amd64

addons:
  apt:
    packages:
      - libxkbcommon-x11-0
      - libgl1-mesa-dev

services: 
  - xvfb

script:
  - sed -i 's/libusb-1.0.0-dev/libusb-1.0-0-dev/g' install.sh
  - sed -i 's/.\/dash/.\/dash > dash.log \&/g' install.sh
  - ./install.sh
  - grep 'Init complete!' dash.log
