language: cpp
sudo: required
compiler:
 - clang
os:
 - linux
dist: focal

addons:
  apt:
    packages:
      - libxkbcommon-x11-0
      - libgl1-mesa-dev

services: 
  - xvfb

script:
  - ./install.sh
